version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: organ-financial-ai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - organ-financial-ai-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: organ-financial-ai-backend
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/organ-financial-ai?authSource=admin
    networks:
      - organ-financial-ai-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: organ-financial-ai-web
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    networks:
      - organ-financial-ai-network

networks:
  finance-ai-network:
    driver: bridge

volumes:
  mongodb_data: