version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: m-finnance-ai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - m-finnance-ai-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: m-finnance-ai-backend
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/m-finnance-ai?authSource=admin
    networks:
      - m-finnance-ai-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: m-finnance-ai-web
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    networks:
      - m-finnance-ai-network

networks:
  m-finnance-ai-network:
    driver: bridge

volumes:
  mongodb_data:
