export const QUERY_KEYS = {
    USER_PROFILE: 'user-profile',
    ACCOUNTS: 'accounts',
    ACCOUNT_SUMMARY: 'account-summary',
    ACCOUNT_DETAIL: (id: string) => ['account', id],
    TRANSACTIONS: 'transactions',
    TRANSACTION_DETAIL: (id: string) => ['transaction', id],
    TRANSACTION_STATS: 'transaction-stats',
    CATEGORIES: 'categories',
    CATEGORY_DETAIL: (id: string) => ['category', id],
    GOALS: 'goals',
    GOAL_DETAIL: (id: string) => ['goal', id],
    GOAL_STATS: 'goal-stats',
    REPORTS_INSIGHTS: 'reports-insights',
    PAYMENT_METHODS: 'payment-methods',
    SUBSCRIPTION: 'subscription',
    INVESTMENTS: 'investments',
    INVESTMENT_SUMMARY: 'investment-summary',
    INVESTMENT_PERFORMANCE: 'investment-performance',
    INVESTMENT_DETAIL: (id: string) => ['investment', id],
    CREDIT_CARDS: 'credit-cards',
    CREDIT_CARD_SUMMARY: 'credit-card-summary',
    CREDIT_CARD_BILLINGS: 'credit-card-billings',
    CREDIT_CARD_DETAIL: (id: string) => ['credit-card', id],
  };